// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}

// FiltersClient is the client API for Filters service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FiltersClient interface {
	Invert(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterReply, error)
	Blur(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterReply, error)
}

type filtersClient struct {
	cc grpc.ClientConnInterface
}

func NewFiltersClient(cc grpc.ClientConnInterface) FiltersClient {
	return &filtersClient{cc}
}

func (c *filtersClient) Invert(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterReply, error) {
	out := new(FilterReply)
	err := c.cc.Invoke(ctx, "/helloworld.Filters/Invert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filtersClient) Blur(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterReply, error) {
	out := new(FilterReply)
	err := c.cc.Invoke(ctx, "/helloworld.Filters/Blur", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FiltersServer is the server API for Filters service.
// All implementations must embed UnimplementedFiltersServer
// for forward compatibility
type FiltersServer interface {
	Invert(context.Context, *FilterRequest) (*FilterReply, error)
	Blur(context.Context, *FilterRequest) (*FilterReply, error)
	mustEmbedUnimplementedFiltersServer()
}

// UnimplementedFiltersServer must be embedded to have forward compatible implementations.
type UnimplementedFiltersServer struct {
}

func (UnimplementedFiltersServer) Invert(context.Context, *FilterRequest) (*FilterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invert not implemented")
}
func (UnimplementedFiltersServer) Blur(context.Context, *FilterRequest) (*FilterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Blur not implemented")
}
func (UnimplementedFiltersServer) mustEmbedUnimplementedFiltersServer() {}

// UnsafeFiltersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FiltersServer will
// result in compilation errors.
type UnsafeFiltersServer interface {
	mustEmbedUnimplementedFiltersServer()
}

func RegisterFiltersServer(s grpc.ServiceRegistrar, srv FiltersServer) {
	s.RegisterService(&Filters_ServiceDesc, srv)
}

func _Filters_Invert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiltersServer).Invert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Filters/Invert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiltersServer).Invert(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filters_Blur_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiltersServer).Blur(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Filters/Blur",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiltersServer).Blur(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Filters_ServiceDesc is the grpc.ServiceDesc for Filters service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Filters_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Filters",
	HandlerType: (*FiltersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invert",
			Handler:    _Filters_Invert_Handler,
		},
		{
			MethodName: "Blur",
			Handler:    _Filters_Blur_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
